apiVersion: v1
kind: ReplicationController
metadata:
  name: k8sdemo
  labels:
    name: k8sdemo
spec:
  replicas: 3   #When the number of copies is 3, k8s will automatically load balance
  selector:
    name: k8sdemo
  template:
    metadata:
      name: k8sdemo
      labels:
        name: k8sdemo
    spec:
      containers:
        - name: k8sdemo
          image: cnode-1:5000/k8sdemo:v1.2  #Image just uploaded to private warehouse
          imagePullPolicy: alwaysPull    #Image pull strategy
          ports:
            - containerPort: 8080